### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by k2d222** [Lich-Corals/Nautilus-fileconverter-43#1]
Thank you for this script, exactly what I wanted!

You state in the readme that the ui freezes while converting. Would it be possible to add a progress bar and a cancel button? Or is there a technical limitation?

E.g. the [nautilus-image-converter](https://gitlab.gnome.org/coreyberla/nautilus-image-converter) extension is able to do so.

**Comment by Lich-Corals** [comment]
> Thank you for this script, exactly what I wanted!
> 
> You state in the readme that the ui freezes while converting. Would it be possible to add a progress bar and a cancel button? Or is there a technical limitation?
> 
> E.g. the [nautilus-image-converter](https://gitlab.gnome.org/coreyberla/nautilus-image-converter) extension is able to do so.

Thanks for the report, 
I tried to add a progress bar or to run the converting operation in the background, without success. The nautilus-image-converter is using a different method to add the extension and a different programming language, so I can't just use their code.

I will try to improve the script, but I can't promise that I will get a progress bar working.

**Comment by Lich-Corals** [comment]
> Thank you for this script, exactly what I wanted!
> 
> You state in the readme that the ui freezes while converting. Would it be possible to add a progress bar and a cancel button? Or is there a technical limitation?
> 
> E.g. the [nautilus-image-converter](https://gitlab.gnome.org/coreyberla/nautilus-image-converter) extension is able to do so.

@k2d222 the UI is no longer freezing with the newest version of the code. derVedro had the idea to run the command for the audio and video converting with the standard nohup function.
Do you see this issue as closed now?

**Comment by k2d222** [comment]
yup, thank you both 🥳
