### ISSUE TITLE
Only two subjects left, can it be used with nemo or thunar? & generally PNG has a compression setting between 0 & 9

### ISSUE THREAD

**Issue by Intellectual234** [Lich-Corals/Nautilus-fileconverter-43#14]
1.) nemo is the only file manager i know that allows the feature to double click of mouse to rename folder/file quickly. Also nemo shows "filesystem/root" shortcut in left hand column unlike Nautilus. :) Although google drive sync stream, appears to work better with nautilus than nemo.

2.) What compression setting does this awesome tool use? on the 0 to 9 scale? And does compressing a PNG using PNG algorithm at highest compression(a level 9) cause loss of quality?

-Thanks!

**Comment by Lich-Corals** [comment]
### 1.)
I don't think it will work with nemo or thunar, the script is built for Nautilus-python only. I don't know if thunar or nemo allow extensions in any way, and if they do, they may use an other programming language. The python functions which are used here, are implemented by nautilus-python, so if thunar or nemo would support extensions with python scripts, I'd have to rewrite the entire script.

You can add a Bookmark to the root dictionary by adding `file:///` as a new line to the `~/.config/gtk-3.0/bookmarks` file and save it. Then you should get a new bookmark like the bottom one here:
![Screenshot from 2023-03-22 12-12-57](https://user-images.githubusercontent.com/111392332/226887729-5c065935-5627-4552-82c2-788eda7049ef.png)

### 2.) 
As far as I tested the tool, it doesn't make the image quality worse. The quality of videos seems to get worse after a convert, but I'm working on it. Here is an test I made, I don't see any loss of quality:
![Screenshot from 2023-03-21 17-03-14](https://user-images.githubusercontent.com/111392332/226888479-ea62a957-5abd-4ef1-ab89-f769aa49429b.png)

Please let me know when I can close the issue. :)

**Comment by Intellectual234** [comment]
@Lich-Corals , thank you very much, yes u can close this. If I had money I would donate money to you & @derVedro.
Are there any other projects you two are working on?

**Comment by Lich-Corals** [comment]
> @Lich-Corals , thank you very much, yes u can close this. If I had money I would donate money to you & @derVedro.
> Are there any other projects you two are working on?

At the time I'm developing a game in my free time. I don't know what derVedro is doing at the time, but [here](https://github.com/derVedro) github page.

**Comment by Intellectual234** [comment]
@Lich-Corals , @derVedro, here's my email, when i get more money I would like to pay either you for your advice & assistance with computer related things. Email me, if you want, so i can have a way to contact you:
my_email111111@protonmail.com

**Comment by derVedro** [comment]
> @Lich-Corals , @derVedro, here's my email, when i get more money I would like to pay either you for your advice & assistance with computer related things. Email me, if you want, so i can have a way to contact you: my_email111111(at) protonmail.com

Thanks for the kind words, but I don't need money. Go to a bar and have a drink on me. If you don't drink alcohol, it can also be a milkshake. :)

Some thoughts to your questions:
1. I am sure it would kind work, I wrote you already how you can approach it. May be it's not a 100% solution, but the right direction to dig.

2. This script is just a wrapper around ffmpeg and Pillow.
2.1.  You can put whatever compression factor you want as some kind of ffmpeg parameter in line 150. It's a simple console call of ffmpeg tool. I think you will have to read a little about it in the [online documentation](https://ffmpeg.org/) or on the man page (`$ man ffmpeg`) or just use google for it. If you found the right options for ffmpeg and tested it in your console, you can edit the 150 line of the script and put it there. That's pretty almost the same command you run on console to convert audio and video. You can adjust parameters, but keep all stuff in curly braces at the same place. This things in curly braces stands as kind of placeholder for input and output files names. 
2.2. For images it's a little bit tricky. The script uses a library called Pillow. That is most common library for image processing for python. I don't really like it, cause every file format has its own set of parameters. For my taste the Pillow [documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html) is not well done. If you wish, you can use some other external tools for image converting. Something like [imagemagick](https://imagemagick.org/index.php) `convert` is pretty nice. You can rewrite the `convert_image` function of the script for `convert` using. Simply copy&paste all the stuff from `convert_audio` and change the system call in `os.system(f"nohup ....`

I think you would have some fun doing all that, learn python and system tools.
