### ISSUE TITLE
Cant convert .heic image files or .avif image files.

### ISSUE THREAD

**Issue by Username23453** [Lich-Corals/Nautilus-fileconverter-43#16]
Just want to say thanks again for making this image converter tool. I do a lot of photo editing & I always use PNG format, so I convert many of my image files in bulk to PNG. However heic & avif dont work & never have. Not sure why?
Could you please help me fix this?
(Tagging @Lich-Corals , &  @derVedro )

-Thanks again!

**Comment by Lich-Corals** [comment]
Sure, I'll take a look at it later. Thanks for reporting.

**Comment by Lich-Corals** [comment]
I just fixed the problem, but you need to install pyheif to convert those files. You can use this command to install it:
```bash
    pip install pyheif
```

**Comment by Lich-Corals** [comment]
Thanks for the feedback @Username23453, I'm not able to reproduce the issue, but your description sounds like an error in the python script.

Could you comment out line 17 (`print = lambda *wish, **verbosity: None`) it the script, by adding an '#' in front of it, then add this line below it: `print(f"VERSION: {pyheif.__version__}")`. 
When that's done, run the `nautilus` command in the terminal, and click some images of different types, the terminal should show something like this: 
```
image/heif
image/avif
image/png
```
If you get any errors referring to the script, please send me those. The terminal should also show something like this: 'VERSION: 0.7.1', this is the version of pyheif you've installed.

**Comment by Lich-Corals** [comment]
Yes @Username23453, you didn't install the updated script. Run the installation commands again, then try the extension again. And be sure to update the right file, the one in /usr/share/ or in ~/.local/share/, depends on where you've installed it.

Here the commands:
- Download the nautilus-fileconverter.py file from the [release page](https://github.com/Lich-Corals/Nautilus-fileconverter-43/releases).
    - Git users can also get the repository with these commands:
        ```bash
            git clone https://github.com/Lich-Corals/Nautilus-fileconverter-43
            
            cd ./Nautilus-fileconverter-43
        ```
- For a systemwide installation move the file to '/usr/share/nautilus-python/extensions/' using this command in the dictonary with the file:
    ```bash
        sudo mv nautilus-fileconverter.py /usr/share/nautilus-python/extensions/nautilus-fileconverter.py
    ```
- For a user spesific installation move the file to '~/.local/share/nautilus-python/extensions/' using this command in the dictonary with the file:
    ```bash
        mv nautilus-fileconverter.py ~/.local/share/nautilus-python/extensions/nautilus-fileconverter.py
    ```
- Now you only have to restart Nautilus using the following commands:
    ```bash
        nautilus -q 

        nohup nautilus & disown
    ```
