### ISSUE TITLE
Another image format that it cant read: .jxl. Please fix. -Thank you.

### ISSUE THREAD

**Issue by Username23453** [Lich-Corals/Nautilus-fileconverter-43#17]
Here's another image format that "Nautilus-fileconverter-43" cant read, .jxl.  I've never even heard of jxl. I guess its fairly new, was created in 2020.   Its an improved updated/version of jpeg/jpg, it appears.
Please update/fix.
-Thank you!

**Comment by Lich-Corals** [comment]
Thanks for the report, I'll take a look at it.

**Comment by Lich-Corals** [comment]
I just pushed the update to the repository. If you've installed the version with automatic updates, it should be there in a couple of minutes...at least if the update feature is really working :D

Just install [jxlpy](https://github.com/Lich-Corals/Nautilus-fileconverter-43/tree/main#jxlpy-jxl) and restart nautilus. Then you should be good to go.

@Username23453
