### ISSUE TITLE
Getting the conversion prop twice in the right-click menue after getting up to date

### ISSUE THREAD

**Issue by Elilorg** [Lich-Corals/Nautilus-fileconverter-43#18]
Hello, first of, thanks a lot for your work ! 
I've encountered a problem, i followed the installation instructions, thinking that the file ```nautilus-fileconverter.py``` would overwrite the precedent version. However, i now have the convert-to option twice in the nautilus. right click menu. The second problem is the git-hub page of this project opens up by itself when opening nautilus sometimes. After removing the file, i got back to only one option. So i assume the extension exists somewhere else on my computer. 
Thanks by advance for you're answer.

**Comment by Lich-Corals** [comment]
Thanks for the report, I will take a look at it soon.


But first, I'd be happy to have a bit more information about your installation:

First of all, where did you install the script? Please check both possible installation dictionaries. (The ones from the installation instructions.)
If there is a file in both dictionaries, I'd strongly recommend removing the one from the root dictionary, if you're only using the extension for one user on your system.

If there's only one file, then please tell me the version that's stored in the second line of the script. There should be a line looking like this: `converterVersion = "001002000"`.


These informations should be enough to solve the issue; I'm looking forward to your response.

**Comment by Elilorg** [comment]
That was it ! i missread the installation part and didn't see there was two folders where it could be installed. I did what you said and everything's looking fine. But i still don't know where the window opening on nautilus startup was. Thanks a lot.

**Comment by Lich-Corals** [comment]
I'm glad it fixed the problem.
The window opening may came from the script trying to update itself in a root location. I'll take a look at it so others won't have the problem in the future.

**Comment by Elilorg** [comment]
Thanks a lot! also yeah the problem is gone now that the only file i have is in .local/share and not the root one.
