### ISSUE TITLE
Nemo files adaption

### ISSUE THREAD

**Issue by Username23453** [Lich-Corals/Nautilus-fileconverter-43#21]
Just wanted you guys to know I gave you guys a shout out and said good things about you guys in the Zorin OS forum.

https://forum.zorin.com/t/nemo-file-manager-wont-thumbnail-preview-avif-files

Thanks again for creating this tool!  its a life saver in linux based OS's!  

@derVedro , @Lich-Corals 

One last think I'll say is that i like Nemo better than nautilus, because you can double click a file or folder and rename it, which is quickest, and which you cant do in nautilus. And it would be cool to be able to use your tool in Nemo. Its more time consuming having to switch to Nautilus. But I'm still glad I can do it in Nautilus! And I use your tool all the time.

**Comment by Lich-Corals** [comment]
Thanks for the feedback, I always appreciate if someone is recommending our program.

I'll take a look at Nemo and it's extending abilities. I can't say if I'm capable of adapting the program for it, but I'll definitely try to.

**Comment by k2d222** [comment]
@Username23453 FYI the <kbd>F2</kbd> key is the standard "rename" key, it works in Nautilus and probably Nemo too :)

**Comment by Lich-Corals** [comment]
> @Lich-Corals , _**"I can't say if I'm capable of adapting the program for it, but I'll definitely try to."**_
> 
> --Try to ask the various A.I.'s for advice, there are quite a few A.I.'s that are good with code also.  And even better when you feed them Python code for dummies pdf's, or linux for dummies pdf's.  I have tons of research notes on this.
> 
> The free A.I.'s though are very buggy, and I dont have the money to pay for better A.I. nor do I have the coding knowledge to fix the buggy prototype scripts/code they create for me.

I'll first try to look at their docs; if I'm lucky, there is a well documented API for Nemo... Just hope I don't have to do it in Java, but this should be very unlikely. :D

**Comment by derVedro** [comment]
> > @Lich-Corals , _**"I can't say if I'm capable of adapting the program for it, but I'll definitely try to."**_
> > --Try to ask the various A.I.'s for advice, there are quite a few A.I.'s that are good with code also.  And even better when you feed them Python code for dummies pdf's, or linux for dummies pdf's.  I have tons of research notes on this.
> > The free A.I.'s though are very buggy, and I dont have the money to pay for better A.I. nor do I have the coding knowledge to fix the buggy prototype scripts/code they create for me.
> 
> I'll first try to look at their docs; if I'm lucky, there is a well documented API for Nemo... Just hope I don't have to do it in Java, but this should be very unlikely. :D

From what I can still remember, it would be pretty easy. basically nautilus and nemo are still very similar, and porting our script is just a matter of a couple lines of code. unfortunately, right now, I don't have time to read the documentation and do the code.

**Comment by Lich-Corals** [comment]
@Username23453, thanks for all the links, I'll definitely take a look at them. Maybe I can get some inspiration on how this program can get improved from those other solutions.

@derVedro, also thanks for your reply; I think I could find the time to read the docs in the next few days or on the weekend.

**Comment by Lich-Corals** [comment]
A quick status update:
I researched a bit in the last few days. So far, it seems like it's much harder to extend Nemo in the way this project would need to.

So far, I mainly tried to create a nemo-action to run the python script with arguments. 
This solution could possibly work by showing up a pop-up with a further context menu, where the user would be able to choose the file format.
For this solution, I'd have to add a new function to the main script, which would run the right converter functions based on arguments given by the nemo-action.
The main problem with this solution is, that nemo-actions can't have any complex logic for the conditions when which context menu should be shown. This means, that I had to add a pop-up, which adds the needed UI, which, for nautilus, would be in a dynamically created submenu.

There seems to be another option to extend Nemo, It's called 'Nemo scripts'. I didn't look at it in detail, but the name at least sounds promising.

My main goal is to create a solution, which is as compact and easy to install as possible, while keeping the simple UI of the converter.
I'll continue researching and trying out different solutions; if someone has further hints on how to achieve this goal, I'd be happy to know their ideas.

**Comment by Lich-Corals** [comment]
@Username23453, I'll continue working on it later. If nothing unexpected interrupts me, I'll hopefully finish the adaption in the next few days or weeks; how soon it'll be depends very strong on how much time I have to work on it.

Thanks for all of your feedback and ideas you shared over the past time; you really help bringing the tool to more people. :)

**Comment by Lich-Corals** [comment]
Status update:
I finally finished the first version of the adaption. You can already import it from the [dev branch](https://github.com/Lich-Corals/Nautilus-fileconverter-43/tree/dev), but it has no documentation so far. If you have Nautilus still installed, you should be able to use the extension by copying the .py and .nemo_action file into the /home/username/.local/share/nemo/actions/ folder. You may need to enable it in the settings.
I'll update the readme soon, but if you want, you can already test it and tell me what you think about it.

**Comment by Lich-Corals** [comment]
Thanks for the feedback!
I added your recommendation to my to-do list for the project. I will first update the readme, then I can have a look at what to do next.

**Comment by derVedro** [comment]
Lol, tonight I ported the nautilus script to nemo too. It really wasn't difficult, as I said, only a few trivial changes were necessary. It works exactly like the nautilus extension. I made a [nemo](https://github.com/derVedro/Nautilus-fileconverter-43/tree/nemo) branch. Check it out.

**Comment by derVedro** [comment]
@Username23453, the script itself is just a wrapper around ffmpeg, look at this [line](https://github.com/derVedro/Nautilus-fileconverter-43/blob/2b30f00706bcd9f7c062fcd00c94c14b8a680f9a/nemo-fileconverter.py#L145). if you simplify it, what happens there is this: `ffmpeg -i INPUT_FILE -strict experimental OUTPUT_FILE.SOME_EXTENTION`
 
Ffmpeg guesses the format by `SOME_EXTENTION` and uses some default values. I can't tell you what the values for each format are, but you can try running ffmpeg in console for your cases yourself and look for them. Ffmpeg is a very cool and multifaceted tool. In principle you can add some additional parameters to the fileconverter script, so that each format is processed in a special way, but I don't see much reason in that.

**Comment by Lich-Corals** [comment]
> derVedro , thanks! thats cool, and it can do audio files and video?    I've been looking for that ever since i moved from windows to linux.  Also when it converts to video, what bitrate is it using and what scanning method? "interlaced" or "progressive"?

Is audio conversion not working in my port, @Username23453?

**Comment by Lich-Corals** [comment]
> @Lich-Corals, i had no idea yours did that? did u mention it did?   Thats cool it does. I just checked and your audio conversion does work for me. :)  Just like how I often convert to PNG, i often convert files to FLAC for editing purposes.

I think I didn't directly mention it, but it is mentioned in the features section of the readme. 
The extension by derVedro is a fork of this one; it's also using the same method, so both should return the same results.

**Comment by Lich-Corals** [comment]
> @Lich-Corals , great job! it works great! :) Thank you! One suggestion for this, an improvement, is that when it creates a new file, I'd recommend telling the script to add more characters to the file name, otherwise, you added multiple PNG output options, if I choose more than one, it will rewrite over themselves, only allowing me to output one PNG file. Also, JPEG is the first option, and i already accidentally clicked it once already, and it converted my jpeg to jpeg, and it lost file size, which i think means it lost quality. And I have no way to "undo" that. I was using it on test images anyway, so I didnt lose anything, but I think adding this feature is a good idea. If you tell it to add to the filename, the jpeg would not have rewritten over itself. I have a script i wrote that is a toolbar button, that converts any clipboard/screenshot image to PNG and auto save to my download folder and renames it random file name characters, however, once i finished this script, someone pointed out that theres no need to tell it to choose a series of random characters for a file name to prevent repetition and error. You can just tell the script to name the file what the current date and time is, as that never repeats itself. I never rewrote the script because it worked fine and I dont have the time to, but let me know if you want my script.
> 
> In summary, i recommend **(original file name) + (date) + (current time, to the second)**

@Username23453, I just published a new release with your suggestion to add timestamps to the filename. Should be working if you update the script (or restart the file manager in a few minutes; auto-updates should detect the update by then.).
I hope this solution is working for you!
